export const REPORT_METRICS_UNITS: Record<string, string> = {
  vo2Max: 'ml/kg/min',
  restingHeartRate: 'bpm',
  underPressureHeartRate: 'bpm',
  bodyFatPercentage: '%',
  leanMuscleMass: 'kg',
  boneDensity: 'g/cm²',
  height: 'cm',
  weight: 'kg',
  oneRepMaxBench: 'kg',
  oneRepMaxSquat: 'kg',
  oneRepMaxDeadlift: 'kg',
  jumpHeight: 'cm',
  averageRunPerKilometer: 'min/km',
  shoulderFlexibility: 'cm',
  hipFlexibility: 'cm',
  balanceTime: 's',
  reactionTime: 'ms',
  coreStabilityScore: 'points',
  hemoglobin: 'g/dL',
  glucose: 'mg/dL',
  creatinine: 'mg/dL',
  vitaminD: 'ng/mL',
  iron: 'µg/dL',
  testosterone: 'ng/dL',
  cortisol: 'µg/dL'
} as const;

export const REPORT_METRICS_RANGES: Record<string, string> = {
  vo2Max: '35.0 - 60.0',
  restingHeartRate: '60 - 90',
  underPressureHeartRate: '120 - 170',
  bodyFatPercentage: '6 - 13',
  leanMuscleMass: '70 - 100',
  boneDensity: '1.21 – 1.355',
  hemoglobin: '13.5 – 17.5',
  glucose: '70.0 – 99.0',
  creatinine: '0.8 - 1.3',
  vitaminD: '30.0 – 50.0',
  iron: '76.0 – 170.0',
  testosterone: '400 - 1000',
  cortisol: '10.0 – 20.0',
  averageRunPerKilometer: '4.0 - 5.0',
  shoulderFlexibility: '70 - 90',
  hipFlexibility: '70 - 95',
  balanceTime: '30 - 60',
  reactionTime: '0.15 - 0.25'
} as const;

export const METRICS_NAMES: string[] = [
  'vo2Max',
  'restingHeartRate',
  'underPressureHeartRate',
  'bodyFatPercentage',
  'leanMuscleMass',
  'boneDensity',
  'height',
  'weight',
  'oneRepMaxBench',
  'oneRepMaxSquat',
  'oneRepMaxDeadlift',
  'jumpHeight',
  'averageRunPerKilometer',
  'shoulderFlexibility',
  'hipFlexibility',
  'balanceTime',
  'reactionTime',
  'coreStabilityScore',
  'hemoglobin',
  'glucose',
  'creatinine',
  'vitaminD',
  'iron',
  'testosterone',
  'cortisol'
] as const;
